name: foobar-dashboard

channels:
  - defaults
  - conda-forge
  - bioconda
  - conda-forge
  - r

dependencies:
  # R
  - r-base=3.6.3
  - r-shinydashboard>=0.7.1
  - r-tidyverse=1.3
  - r-shiny=1.5
  - r-rsqlite=2.2
  - r-DBI=1.1
  - r-visnetwork=2.0.6
  - r-irkernel=0.8.15
  - r-plotly=4.9.2.1
  - r-dt=0.5
  - r-stringi>=1.4.6
  - r-memoise=1.1
  - r-wordcloud=2.6
  - r-tm=0.7
  - r-nlp=0.2
  - r-slam=0.1_47
  - r-snowballc=0.7

  # jupyter notebooks
  - jupyterlab>=2.2.4
